import { useState } from "react";

const ERROR_MESSAGES = {
  network: "Couldn't reach the server. Check your connection.",
  422: "The kitchen had a moment — please try again",
  429: "Whoa, slow down! Give it a moment before trying again",
  503: "Our chef is busy — try again in a few seconds",
  500: "Something went wrong on our end — try again",
  empty: "Hmm, nothing came to mind. Try adding more ingredients!",
};

function mapError(status, detail) {
  if (status && ERROR_MESSAGES[status]) return ERROR_MESSAGES[status];
  if (status === 400 && detail) return detail;
  return "Something went wrong — try again";
}

export default function App() {
  const [input, setInput] = useState("");
  const [ingredients, setIngredients] = useState([]);
  const [recipes, setRecipes] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  function addIngredient(raw) {
    const items = raw
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    if (items.length === 0) return;

    setIngredients((prev) => {
      const existing = new Set(prev.map((s) => s.toLowerCase()));
      const unique = items.filter((item) => !existing.has(item.toLowerCase()));
      return [...prev, ...unique];
    });
    setInput("");
    setError(null);
    setRecipes(null);
  }

  function removeIngredient(idx) {
    setIngredients((prev) => prev.filter((_, i) => i !== idx));
    setError(null);
    setRecipes(null);
  }

  function handleKeyDown(e) {
    if (e.key === "Enter") {
      e.preventDefault();
      addIngredient(input);
    }
  }

  async function generateRecipes() {
    if (ingredients.length === 0 || loading) return;

    setLoading(true);
    setError(null);
    setRecipes(null);

    try {
      const res = await fetch("/api/generate-recipe", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ingredients }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw { status: res.status, detail: body.detail };
      }

      const data = await res.json();

      if (!data.recipes || data.recipes.length === 0) {
        setError({ message: ERROR_MESSAGES.empty, status: null });
      } else {
        setRecipes(data.recipes);
      }
    } catch (err) {
      if (err instanceof TypeError) {
        setError({ message: ERROR_MESSAGES.network, status: null });
      } else if (err.status) {
        setError({
          message: mapError(err.status, err.detail),
          status: err.status,
        });
      } else {
        setError({ message: ERROR_MESSAGES[500], status: 500 });
      }
    } finally {
      setLoading(false);
    }
  }

  function dismissError() {
    setError(null);
  }

  return (
    <div className="app">
      <header className="header">
        <div className="header-brand">
          <span className="header-icon">&#x1F468;&#x200D;&#x1F373;</span>
          <h1 className="header-title">Pantry Chef</h1>
        </div>
        <p className="header-sub">What&apos;s in your pantry? Let&apos;s cook.</p>
        <p className="header-disclaimer">
          &#x26A0; Recipes are AI-generated by Claude. Always use your best judgment when cooking.
        </p>
      </header>

      <main className="main">
        <div className="input-area">
          <div className="input-row">
            <input
              className="ingredient-input"
              type="text"
              placeholder="Type an ingredient, then press Enter (e.g. chicken, garlic, pasta)"
              value={input}
              onChange={(e) => {
                setInput(e.target.value);
                setError(null);
              }}
              onKeyDown={handleKeyDown}
            />
            <button
              className="add-btn"
              onClick={() => addIngredient(input)}
              disabled={!input.trim()}
              aria-label="Add ingredient"
            >
              +
            </button>
          </div>

          {ingredients.length > 0 && (
            <div className="ingredient-tags">
              {ingredients.map((item, i) => (
                <span key={i} className="tag">
                  {item}
                  <button
                    className="tag-remove"
                    onClick={() => removeIngredient(i)}
                    aria-label={`Remove ${item}`}
                  >
                    &times;
                  </button>
                </span>
              ))}
            </div>
          )}

          <button
            className="generate-btn"
            onClick={generateRecipes}
            disabled={ingredients.length === 0 || loading}
          >
            {loading ? (
              <span className="spinner-row">
                <span className="spinner" />
                Cooking up ideas...
              </span>
            ) : (
              "Generate Recipes"
            )}
          </button>
        </div>

        {error && (
          <div className="error-banner">
            <span className="error-msg">{error.message}</span>
            <button className="error-dismiss" onClick={dismissError} aria-label="Dismiss error">
              &times;
            </button>
          </div>
        )}

        {recipes && recipes.length > 0 && (
          <div className="recipe-grid">
            {recipes.map((r, i) => (
              <div key={i} className="recipe-card">
                <div className="recipe-header">
                  <h2 className="recipe-title">{r.title}</h2>
                  <p className="recipe-desc">{r.description}</p>
                  <div className="recipe-meta">
                    <span className="meta-badge">{r.difficulty}</span>
                    <span className="meta-badge">{r.cook_time}</span>
                  </div>
                </div>

                <div className="recipe-body">
                  <div className="recipe-section">
                    <h3>Ingredients</h3>
                    <ul className="ingredient-list">
                      {r.ingredients.map((ing, j) => (
                        <li key={j}>{ing}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="recipe-section">
                    <h3>Steps</h3>
                    <ol className="step-list">
                      {r.steps.map((step, j) => (
                        <li key={j}>{step}</li>
                      ))}
                    </ol>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {!recipes && !loading && !error && ingredients.length === 0 && (
          <div className="empty-state">
            <div className="empty-icon">&#x1F373;</div>
            <p className="empty-title">Your Pantry Chef</p>
            <p className="empty-sub">
              Add ingredients from your pantry and fridge above, then generate recipes.
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
